language: cpp

compiler:
  - gcc
  - clang

before_script:
  - cd test
  - mkdir build
  - cd build
  - cmake ..

install:
  # Install newer cmake
  - CMAKE_VERSION=3.11.1
  - cmake --version
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xzv -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

script: make && make test
