language: cpp

compiler:
  - gcc
  - clang

before_script:
  - cd test
  - mkdir build
  - cd build
  - cmake ..

script: make && make test

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.sh
  - chmod +x cmake-3.11.1-Linux-x86_64.sh
  - ./cmake-3.11.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
